PR Equipo 5
cambranes/ProgramacionEstructurada pull request #38
Opened 2019-02-13 12:36 UTC by amaurymc

2019-02-13 17:16 UTC, cambranes approved these changes

2019-02-13 17:20 UTC, cambranes requested changes
Hay un conflicto en el merge con el ejercicio 46, podrían verificar si a ustedes les correspondía o el archivo fue nombrado incorrectamente

2019-02-13 17:33 UTC, amaurymc commented
> Hay un conflicto en el merge con el ejercicio 46, podrían verificar si a ustedes les correspondía o el archivo fue nombrado incorrectamente

Es un error en la división de ejercicios. En el ADA hay dos equipos a los cuales les tocaron el ejercicio 46.

2019-02-14 20:38 UTC, cambranes approved these changes

2019-02-14 20:38 UTC, merged